### ISSUE TITLE
Dart client for flutter

### ISSUE THREAD

**Issue by faysou** [kamalshkeir/ksbus#1]
Interesting project, this is more an idea than an issue, it would be interesting to have a dart/flutter client like for JavaScript.

**Comment by kamalshkeir** [comment]
why not, it's a good idea, and if you want to contribute making this client you are welcome, it should be very easy as all you need to do is wrapping a ws connection in a Bus Class, you just need to follow the same api as js or go clients.

Also feel free to join the other discussion https://github.com/kamalshkeir/kago/discussions/7
