### ISSUE TITLE
Benchmark?

### ISSUE THREAD

**Issue by kokizzu** [kamalshkeir/ksbus#2]
compared to other websocket/socketio libraries

**Comment by kamalshkeir** [comment]
you did this benchmark ?

**Comment by kokizzu** [comment]
nope, just asking whether such benchmark exists :3 
at least i like the API better than other RPCs, this one similar to NATS

**Comment by kamalshkeir** [comment]
Thank you, Glad you like it :) 
It still in early stages for benchmarks, i need to make tests to ensure everything still working before, but whenever i finish i will do a lot of benchmarks

And feel free to join our other discussions https://github.com/kamalshkeir/kago/discussions/7
